spring.application.name=backend
server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postgresql://localhost:5432/slabi
spring.datasource.username=slabi
spring.datasource.password=slabi

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
